apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/dvorkinguy/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

  # Add the Ingress resource here
  additionalObjects:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: myapp-ingress
        namespace: myapp
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/tls-acme: 'true'
          nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
          nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
      spec:
        rules:
          - host: app.devopschallenges.com
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: myapp
                      port:
                        name: https
        tls:
          - hosts:
              - app.devopschallenges.com
            secretName: app-tls
