apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/dvorkinguy/argocd-app-config.git
    targetRevision: HEAD
    path: dev

    # Add the Helm chart values file that includes the Ingress resource
    helm:
      valueFiles:
        - dev/ingress.yaml  # Provide the path to the Helm values file that contains the Ingress resource

  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
